// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: proto/model/cmd.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdCode int32

const (
	CmdCode_RunOSCmd           CmdCode = 0
	CmdCode_RunAddAttackSource CmdCode = 1
	CmdCode_RunAddAttack       CmdCode = 2
	CmdCode_RunAddDict         CmdCode = 3
)

// Enum value maps for CmdCode.
var (
	CmdCode_name = map[int32]string{
		0: "RunOSCmd",
		1: "RunAddAttackSource",
		2: "RunAddAttack",
		3: "RunAddDict",
	}
	CmdCode_value = map[string]int32{
		"RunOSCmd":           0,
		"RunAddAttackSource": 1,
		"RunAddAttack":       2,
		"RunAddDict":         3,
	}
)

func (x CmdCode) Enum() *CmdCode {
	p := new(CmdCode)
	*p = x
	return p
}

func (x CmdCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_model_cmd_proto_enumTypes[0].Descriptor()
}

func (CmdCode) Type() protoreflect.EnumType {
	return &file_proto_model_cmd_proto_enumTypes[0]
}

func (x CmdCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdCode.Descriptor instead.
func (CmdCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_model_cmd_proto_rawDescGZIP(), []int{0}
}

type CmdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeIdS []string `protobuf:"bytes,1,rep,name=nodeIdS,proto3" json:"nodeIdS,omitempty"`
	// the cmd that needs running
	Cmd *Cmd `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	//this os that can run this cmd
	Os string `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
}

func (x *CmdRequest) Reset() {
	*x = CmdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_cmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRequest) ProtoMessage() {}

func (x *CmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_cmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRequest.ProtoReflect.Descriptor instead.
func (*CmdRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_cmd_proto_rawDescGZIP(), []int{0}
}

func (x *CmdRequest) GetNodeIdS() []string {
	if x != nil {
		return x.NodeIdS
	}
	return nil
}

func (x *CmdRequest) GetCmd() *Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *CmdRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type CmdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the node that run this cmd
	NodeId string `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	//the run cmd status,0----ok,-1----failed
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	//the time that runned cmd
	Time uint64 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	// run cmd results
	Contents []byte `protobuf:"bytes,4,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *CmdReply) Reset() {
	*x = CmdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_cmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdReply) ProtoMessage() {}

func (x *CmdReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_cmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdReply.ProtoReflect.Descriptor instead.
func (*CmdReply) Descriptor() ([]byte, []int) {
	return file_proto_model_cmd_proto_rawDescGZIP(), []int{1}
}

func (x *CmdReply) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CmdReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CmdReply) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CmdReply) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type Cmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//cmd code
	Code CmdCode `protobuf:"varint,1,opt,name=code,proto3,enum=sbot.proto.model.CmdCode" json:"code,omitempty"`
	//cmd name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// cmd args
	Args []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *Cmd) Reset() {
	*x = Cmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_cmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd) ProtoMessage() {}

func (x *Cmd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_cmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd.ProtoReflect.Descriptor instead.
func (*Cmd) Descriptor() ([]byte, []int) {
	return file_proto_model_cmd_proto_rawDescGZIP(), []int{2}
}

func (x *Cmd) GetCode() CmdCode {
	if x != nil {
		return x.Code
	}
	return CmdCode_RunOSCmd
}

func (x *Cmd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cmd) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_proto_model_cmd_proto protoreflect.FileDescriptor

var file_proto_model_cmd_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x63, 0x6d,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x5f, 0x0a, 0x0a, 0x43, 0x6d, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x53, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x53, 0x12, 0x27, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x73, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x22, 0x6a, 0x0a, 0x08, 0x43, 0x6d,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x5c, 0x0a, 0x03, 0x43, 0x6d, 0x64, 0x12, 0x2d, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x73, 0x62,
	0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43,
	0x6d, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x2a, 0x51, 0x0a, 0x07, 0x43, 0x6d, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x0c, 0x0a, 0x08, 0x52, 0x75, 0x6e, 0x4f, 0x53, 0x43, 0x6d, 0x64, 0x10, 0x00, 0x12, 0x16, 0x0a,
	0x12, 0x52, 0x75, 0x6e, 0x41, 0x64, 0x64, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x75, 0x6e, 0x41, 0x64, 0x64, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x6b, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x41, 0x64,
	0x64, 0x44, 0x69, 0x63, 0x74, 0x10, 0x03, 0x42, 0x68, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x62, 0x77, 0x33, 0x62, 0x61, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x03, 0x43, 0x6d, 0x64, 0x50, 0x01, 0x5a, 0x1b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x62, 0x6f, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0xaa, 0x02, 0x10, 0x53, 0x42,
	0x6f, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0xca, 0x02,
	0x10, 0x53, 0x42, 0x6f, 0x74, 0x5c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5c, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_model_cmd_proto_rawDescOnce sync.Once
	file_proto_model_cmd_proto_rawDescData = file_proto_model_cmd_proto_rawDesc
)

func file_proto_model_cmd_proto_rawDescGZIP() []byte {
	file_proto_model_cmd_proto_rawDescOnce.Do(func() {
		file_proto_model_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_cmd_proto_rawDescData)
	})
	return file_proto_model_cmd_proto_rawDescData
}

var file_proto_model_cmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_model_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_model_cmd_proto_goTypes = []interface{}{
	(CmdCode)(0),       // 0: sbot.proto.model.CmdCode
	(*CmdRequest)(nil), // 1: sbot.proto.model.CmdRequest
	(*CmdReply)(nil),   // 2: sbot.proto.model.CmdReply
	(*Cmd)(nil),        // 3: sbot.proto.model.Cmd
}
var file_proto_model_cmd_proto_depIdxs = []int32{
	3, // 0: sbot.proto.model.CmdRequest.cmd:type_name -> sbot.proto.model.Cmd
	0, // 1: sbot.proto.model.Cmd.code:type_name -> sbot.proto.model.CmdCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_model_cmd_proto_init() }
func file_proto_model_cmd_proto_init() {
	if File_proto_model_cmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_model_cmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_cmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_cmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_cmd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_cmd_proto_goTypes,
		DependencyIndexes: file_proto_model_cmd_proto_depIdxs,
		EnumInfos:         file_proto_model_cmd_proto_enumTypes,
		MessageInfos:      file_proto_model_cmd_proto_msgTypes,
	}.Build()
	File_proto_model_cmd_proto = out.File
	file_proto_model_cmd_proto_rawDesc = nil
	file_proto_model_cmd_proto_goTypes = nil
	file_proto_model_cmd_proto_depIdxs = nil
}
