// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: proto/model/attacktask.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OsType int32

const (
	OsType_Linux   OsType = 0
	OsType_Windows OsType = 1
	OsType_Macos   OsType = 2
)

// Enum value maps for OsType.
var (
	OsType_name = map[int32]string{
		0: "Linux",
		1: "Windows",
		2: "Macos",
	}
	OsType_value = map[string]int32{
		"Linux":   0,
		"Windows": 1,
		"Macos":   2,
	}
)

func (x OsType) Enum() *OsType {
	p := new(OsType)
	*p = x
	return p
}

func (x OsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OsType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_model_attacktask_proto_enumTypes[0].Descriptor()
}

func (OsType) Type() protoreflect.EnumType {
	return &file_proto_model_attacktask_proto_enumTypes[0]
}

func (x OsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OsType.Descriptor instead.
func (OsType) EnumDescriptor() ([]byte, []int) {
	return file_proto_model_attacktask_proto_rawDescGZIP(), []int{0}
}

type CreateAttackTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Host       string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port       int32  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	User       string `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Passwd     string `protobuf:"bytes,6,opt,name=passwd,proto3" json:"passwd,omitempty"`
	PrivateKey string `protobuf:"bytes,7,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	OsType     OsType `protobuf:"varint,8,opt,name=osType,proto3,enum=sbot.proto.model.OsType" json:"osType,omitempty"`
	Cbot       string `protobuf:"bytes,9,opt,name=cbot,proto3" json:"cbot,omitempty"`
	Time       uint64 `protobuf:"varint,10,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *CreateAttackTaskRequest) Reset() {
	*x = CreateAttackTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_attacktask_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAttackTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttackTaskRequest) ProtoMessage() {}

func (x *CreateAttackTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_attacktask_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttackTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateAttackTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_attacktask_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAttackTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAttackTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAttackTaskRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CreateAttackTaskRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CreateAttackTaskRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CreateAttackTaskRequest) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *CreateAttackTaskRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *CreateAttackTaskRequest) GetOsType() OsType {
	if x != nil {
		return x.OsType
	}
	return OsType_Linux
}

func (x *CreateAttackTaskRequest) GetCbot() string {
	if x != nil {
		return x.Cbot
	}
	return ""
}

func (x *CreateAttackTaskRequest) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type CreateAttackTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	TaskId string `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (x *CreateAttackTaskReply) Reset() {
	*x = CreateAttackTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_attacktask_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAttackTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttackTaskReply) ProtoMessage() {}

func (x *CreateAttackTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_attacktask_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttackTaskReply.ProtoReflect.Descriptor instead.
func (*CreateAttackTaskReply) Descriptor() ([]byte, []int) {
	return file_proto_model_attacktask_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAttackTaskReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateAttackTaskReply) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_proto_model_attacktask_proto protoreflect.FileDescriptor

var file_proto_model_attacktask_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x73, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x22, 0x93, 0x02, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x6b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x77, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x30, 0x0a, 0x06,
	0x6f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x73,
	0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x4f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x62, 0x6f, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x62,
	0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x2a,
	0x2b, 0x0a, 0x06, 0x4f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x69, 0x6e,
	0x75, 0x78, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x61, 0x63, 0x6f, 0x73, 0x10, 0x02, 0x42, 0x6f, 0x0a, 0x1c,
	0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x62, 0x77, 0x33, 0x62, 0x61, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x0a, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x01, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0xaa, 0x02, 0x10, 0x53, 0x42, 0x6f, 0x74, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0xca, 0x02, 0x10, 0x53, 0x42, 0x6f,
	0x74, 0x5c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_model_attacktask_proto_rawDescOnce sync.Once
	file_proto_model_attacktask_proto_rawDescData = file_proto_model_attacktask_proto_rawDesc
)

func file_proto_model_attacktask_proto_rawDescGZIP() []byte {
	file_proto_model_attacktask_proto_rawDescOnce.Do(func() {
		file_proto_model_attacktask_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_attacktask_proto_rawDescData)
	})
	return file_proto_model_attacktask_proto_rawDescData
}

var file_proto_model_attacktask_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_model_attacktask_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_model_attacktask_proto_goTypes = []interface{}{
	(OsType)(0),                     // 0: sbot.proto.model.OsType
	(*CreateAttackTaskRequest)(nil), // 1: sbot.proto.model.CreateAttackTaskRequest
	(*CreateAttackTaskReply)(nil),   // 2: sbot.proto.model.CreateAttackTaskReply
}
var file_proto_model_attacktask_proto_depIdxs = []int32{
	0, // 0: sbot.proto.model.CreateAttackTaskRequest.osType:type_name -> sbot.proto.model.OsType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_model_attacktask_proto_init() }
func file_proto_model_attacktask_proto_init() {
	if File_proto_model_attacktask_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_model_attacktask_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAttackTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_attacktask_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAttackTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_attacktask_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_attacktask_proto_goTypes,
		DependencyIndexes: file_proto_model_attacktask_proto_depIdxs,
		EnumInfos:         file_proto_model_attacktask_proto_enumTypes,
		MessageInfos:      file_proto_model_attacktask_proto_msgTypes,
	}.Build()
	File_proto_model_attacktask_proto = out.File
	file_proto_model_attacktask_proto_rawDesc = nil
	file_proto_model_attacktask_proto_goTypes = nil
	file_proto_model_attacktask_proto_depIdxs = nil
}
