// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: proto/model/attack_payload.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakeJarAttackPayloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	NodeId string `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Cmd    string `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
}

func (x *MakeJarAttackPayloadRequest) Reset() {
	*x = MakeJarAttackPayloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_attack_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeJarAttackPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeJarAttackPayloadRequest) ProtoMessage() {}

func (x *MakeJarAttackPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_attack_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeJarAttackPayloadRequest.ProtoReflect.Descriptor instead.
func (*MakeJarAttackPayloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_attack_payload_proto_rawDescGZIP(), []int{0}
}

func (x *MakeJarAttackPayloadRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MakeJarAttackPayloadRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MakeJarAttackPayloadRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type MakeJarAttackPayloadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Length  uint64 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *MakeJarAttackPayloadReply) Reset() {
	*x = MakeJarAttackPayloadReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_attack_payload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeJarAttackPayloadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeJarAttackPayloadReply) ProtoMessage() {}

func (x *MakeJarAttackPayloadReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_attack_payload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeJarAttackPayloadReply.ProtoReflect.Descriptor instead.
func (*MakeJarAttackPayloadReply) Descriptor() ([]byte, []int) {
	return file_proto_model_attack_payload_proto_rawDescGZIP(), []int{1}
}

func (x *MakeJarAttackPayloadReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MakeJarAttackPayloadReply) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *MakeJarAttackPayloadReply) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_proto_model_attack_payload_proto protoreflect.FileDescriptor

var file_proto_model_attack_payload_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x73, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x22, 0x5f, 0x0a, 0x1b, 0x4d, 0x61, 0x6b, 0x65, 0x4a, 0x61, 0x72, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x6b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x63, 0x6d, 0x64, 0x22, 0x65, 0x0a, 0x19, 0x4d, 0x61, 0x6b, 0x65, 0x4a, 0x61, 0x72,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x71, 0x0a, 0x1c,
	0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x62, 0x77, 0x33, 0x62, 0x61, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x0c, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x50, 0x61, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x01, 0x5a, 0x1b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0xaa, 0x02, 0x10, 0x53, 0x42, 0x6f, 0x74,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0xca, 0x02, 0x10, 0x53,
	0x42, 0x6f, 0x74, 0x5c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_model_attack_payload_proto_rawDescOnce sync.Once
	file_proto_model_attack_payload_proto_rawDescData = file_proto_model_attack_payload_proto_rawDesc
)

func file_proto_model_attack_payload_proto_rawDescGZIP() []byte {
	file_proto_model_attack_payload_proto_rawDescOnce.Do(func() {
		file_proto_model_attack_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_attack_payload_proto_rawDescData)
	})
	return file_proto_model_attack_payload_proto_rawDescData
}

var file_proto_model_attack_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_model_attack_payload_proto_goTypes = []interface{}{
	(*MakeJarAttackPayloadRequest)(nil), // 0: sbot.proto.model.MakeJarAttackPayloadRequest
	(*MakeJarAttackPayloadReply)(nil),   // 1: sbot.proto.model.MakeJarAttackPayloadReply
}
var file_proto_model_attack_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_model_attack_payload_proto_init() }
func file_proto_model_attack_payload_proto_init() {
	if File_proto_model_attack_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_model_attack_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeJarAttackPayloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_attack_payload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeJarAttackPayloadReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_attack_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_attack_payload_proto_goTypes,
		DependencyIndexes: file_proto_model_attack_payload_proto_depIdxs,
		MessageInfos:      file_proto_model_attack_payload_proto_msgTypes,
	}.Build()
	File_proto_model_attack_payload_proto = out.File
	file_proto_model_attack_payload_proto_rawDesc = nil
	file_proto_model_attack_payload_proto_goTypes = nil
	file_proto_model_attack_payload_proto_depIdxs = nil
}
