// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: proto/model/attack_targets.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type

AddAttackTargetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CfgId          string   `protobuf:"bytes,1,opt,name=cfgId,proto3" json:"cfgId,omitempty"`
	Name           string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Proto          string   `protobuf:"bytes,3,opt,name=proto,proto3" json:"proto,omitempty"`
	App            string   `protobuf:"bytes,4,opt,name=app,proto3" json:"app,omitempty"`
	Key            string   `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Query          string   `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	UseDefaultPort bool     `protobuf:"varint,7,opt,name=useDefaultPort,proto3" json:"useDefaultPort,omitempty"`
	NodeIds        []string `protobuf:"bytes,8,rep,name=nodeIds,proto3" json:"nodeIds,omitempty"`
	AttackTypes    []string `protobuf:"bytes,9,rep,name=attackTypes,proto3" json:"attackTypes,omitempty"`
	WhiteLists     []string `protobuf:"bytes,10,rep,name=whiteLists,proto3" json:"whiteLists,omitempty"`
	BlackLists     []string `protobuf:"bytes,11,rep,name=blackLists,proto3" json:"blackLists,omitempty"`
}

func (x *AddAttackTargetsRequest) Reset() {
	*x = AddAttackTargetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_attack_targets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAttackTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAttackTargetsRequest) ProtoMessage() {}

func (x *AddAttackTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_attack_targets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAttackTargetsRequest.ProtoReflect.Descriptor instead.
func (*AddAttackTargetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_attack_targets_proto_rawDescGZIP(), []int{0}
}

func (x *AddAttackTargetsRequest) GetCfgId() string {
	if x != nil {
		return x.CfgId
	}
	return ""
}

func (x *AddAttackTargetsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddAttackTargetsRequest) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *AddAttackTargetsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *AddAttackTargetsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AddAttackTargetsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AddAttackTargetsRequest) GetUseDefaultPort() bool {
	if x != nil {
		return x.UseDefaultPort
	}
	return false
}

func (x *AddAttackTargetsRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *AddAttackTargetsRequest) GetAttackTypes() []string {
	if x != nil {
		return x.AttackTypes
	}
	return nil
}

func (x *AddAttackTargetsRequest) GetWhiteLists() []string {
	if x != nil {
		return x.WhiteLists
	}
	return nil
}

func (x *AddAttackTargetsRequest) GetBlackLists() []string {
	if x != nil {
		return x.BlackLists
	}
	return nil
}

type AddAttackTargetsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message      string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FetchedNodes []string `protobuf:"bytes,3,rep,name=fetchedNodes,proto3" json:"fetchedNodes,omitempty"`
}

func (x *AddAttackTargetsReply) Reset() {
	*x = AddAttackTargetsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_attack_targets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAttackTargetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAttackTargetsReply) ProtoMessage() {}

func (x *AddAttackTargetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_attack_targets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAttackTargetsReply.ProtoReflect.Descriptor instead.
func (*AddAttackTargetsReply) Descriptor() ([]byte, []int) {
	return file_proto_model_attack_targets_proto_rawDescGZIP(), []int{1}
}

func (x *AddAttackTargetsReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddAttackTargetsReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddAttackTargetsReply) GetFetchedNodes() []string {
	if x != nil {
		return x.FetchedNodes
	}
	return nil
}

type FetchAttackTargetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
}

func (x *FetchAttackTargetsRequest) Reset() {
	*x = FetchAttackTargetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_attack_targets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAttackTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAttackTargetsRequest) ProtoMessage() {}

func (x *FetchAttackTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_attack_targets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAttackTargetsRequest.ProtoReflect.Descriptor instead.
func (*FetchAttackTargetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_attack_targets_proto_rawDescGZIP(), []int{2}
}

func (x *FetchAttackTargetsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type AttackTargets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size        uint64   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	AttackTypes []string `protobuf:"bytes,3,rep,name=attackTypes,proto3" json:"attackTypes,omitempty"`
	Content     []byte   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *AttackTargets) Reset() {
	*x = AttackTargets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_attack_targets_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttackTargets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackTargets) ProtoMessage() {}

func (x *AttackTargets) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_attack_targets_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackTargets.ProtoReflect.Descriptor instead.
func (*AttackTargets) Descriptor() ([]byte, []int) {
	return file_proto_model_attack_targets_proto_rawDescGZIP(), []int{3}
}

func (x *AttackTargets) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttackTargets) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AttackTargets) GetAttackTypes() []string {
	if x != nil {
		return x.AttackTypes
	}
	return nil
}

func (x *AttackTargets) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_proto_model_attack_targets_proto protoreflect.FileDescriptor

var file_proto_model_attack_targets_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x73, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x22, 0xb7, 0x02, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x6b, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x66, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x66, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61,
	0x70, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x75, 0x73,
	0x65, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0e, 0x75, 0x73, 0x65, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b,
	0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x77, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x77, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x22, 0x6d,
	0x0a, 0x15, 0x41, 0x64, 0x64, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x65, 0x74,
	0x63, 0x68, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0c, 0x66, 0x65, 0x74, 0x63, 0x68, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x33, 0x0a,
	0x19, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x22, 0x73, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61,
	0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x72, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x67,
	0x62, 0x77, 0x33, 0x62, 0x61, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x0d, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x50, 0x01, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0xaa, 0x02, 0x10, 0x53, 0x42, 0x6f, 0x74, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0xca, 0x02, 0x10, 0x53, 0x42, 0x6f, 0x74, 0x5c,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_model_attack_targets_proto_rawDescOnce sync.Once
	file_proto_model_attack_targets_proto_rawDescData = file_proto_model_attack_targets_proto_rawDesc
)

func file_proto_model_attack_targets_proto_rawDescGZIP() []byte {
	file_proto_model_attack_targets_proto_rawDescOnce.Do(func() {
		file_proto_model_attack_targets_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_attack_targets_proto_rawDescData)
	})
	return file_proto_model_attack_targets_proto_rawDescData
}

var file_proto_model_attack_targets_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_model_attack_targets_proto_goTypes = []interface{}{
	(*AddAttackTargetsRequest)(nil),   // 0: sbot.proto.model.AddAttackTargetsRequest
	(*AddAttackTargetsReply)(nil),     // 1: sbot.proto.model.AddAttackTargetsReply
	(*FetchAttackTargetsRequest)(nil), // 2: sbot.proto.model.FetchAttackTargetsRequest
	(*AttackTargets)(nil),             // 3: sbot.proto.model.AttackTargets
}
var file_proto_model_attack_targets_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_model_attack_targets_proto_init() }
func file_proto_model_attack_targets_proto_init() {
	if File_proto_model_attack_targets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_model_attack_targets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAttackTargetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_attack_targets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAttackTargetsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_attack_targets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchAttackTargetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_attack_targets_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttackTargets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_attack_targets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_attack_targets_proto_goTypes,
		DependencyIndexes: file_proto_model_attack_targets_proto_depIdxs,
		MessageInfos:      file_proto_model_attack_targets_proto_msgTypes,
	}.Build()
	File_proto_model_attack_targets_proto = out.File
	file_proto_model_attack_targets_proto_rawDesc = nil
	file_proto_model_attack_targets_proto_goTypes = nil
	file_proto_model_attack_targets_proto_depIdxs = nil
}
