// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: proto/model/attack_scripts.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddAttackScriptsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CfgIds  []string `protobuf:"bytes,1,rep,name=cfgIds,proto3" json:"cfgIds,omitempty"`
	NodeIds []string `protobuf:"bytes,2,rep,name=nodeIds,proto3" json:"nodeIds,omitempty"`
}

func (x *AddAttackScriptsRequest) Reset() {
	*x = AddAttackScriptsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_attack_scripts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAttackScriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAttackScriptsRequest) ProtoMessage() {}

func (x *AddAttackScriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_attack_scripts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAttackScriptsRequest.ProtoReflect.Descriptor instead.
func (*AddAttackScriptsRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_attack_scripts_proto_rawDescGZIP(), []int{0}
}

func (x *AddAttackScriptsRequest) GetCfgIds() []string {
	if x != nil {
		return x.CfgIds
	}
	return nil
}

func (x *AddAttackScriptsRequest) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type AddAttackScriptsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message      string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FetchedNodes []string `protobuf:"bytes,3,rep,name=fetchedNodes,proto3" json:"fetchedNodes,omitempty"`
}

func (x *AddAttackScriptsReply) Reset() {
	*x = AddAttackScriptsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_attack_scripts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAttackScriptsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAttackScriptsReply) ProtoMessage() {}

func (x *AddAttackScriptsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_attack_scripts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAttackScriptsReply.ProtoReflect.Descriptor instead.
func (*AddAttackScriptsReply) Descriptor() ([]byte, []int) {
	return file_proto_model_attack_scripts_proto_rawDescGZIP(), []int{1}
}

func (x *AddAttackScriptsReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddAttackScriptsReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddAttackScriptsReply) GetFetchedNodes() []string {
	if x != nil {
		return x.FetchedNodes
	}
	return nil
}

type FetchAttackScriptsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
}

func (x *FetchAttackScriptsRequest) Reset() {
	*x = FetchAttackScriptsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_attack_scripts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAttackScriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAttackScriptsRequest) ProtoMessage() {}

func (x *FetchAttackScriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_attack_scripts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAttackScriptsRequest.ProtoReflect.Descriptor instead.
func (*FetchAttackScriptsRequest) Descriptor() ([]byte, []int) {
	return file_proto_model_attack_scripts_proto_rawDescGZIP(), []int{2}
}

func (x *FetchAttackScriptsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type AttackScripts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AttackType   string `protobuf:"bytes,2,opt,name=attackType,proto3" json:"attackType,omitempty"`
	DefaultPort  int32  `protobuf:"varint,3,opt,name=defaultPort,proto3" json:"defaultPort,omitempty"`
	DefaultProto string `protobuf:"bytes,4,opt,name=defaultProto,proto3" json:"defaultProto,omitempty"`
	Size         uint64 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Content      []byte `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	HasNext      bool   `protobuf:"varint,7,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
}

func (x *AttackScripts) Reset() {
	*x = AttackScripts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_attack_scripts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttackScripts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackScripts) ProtoMessage() {}

func (x *AttackScripts) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_attack_scripts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackScripts.ProtoReflect.Descriptor instead.
func (*AttackScripts) Descriptor() ([]byte, []int) {
	return file_proto_model_attack_scripts_proto_rawDescGZIP(), []int{3}
}

func (x *AttackScripts) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttackScripts) GetAttackType() string {
	if x != nil {
		return x.AttackType
	}
	return ""
}

func (x *AttackScripts) GetDefaultPort() int32 {
	if x != nil {
		return x.DefaultPort
	}
	return 0
}

func (x *AttackScripts) GetDefaultProto() string {
	if x != nil {
		return x.DefaultProto
	}
	return ""
}

func (x *AttackScripts) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AttackScripts) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AttackScripts) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

var File_proto_model_attack_scripts_proto protoreflect.FileDescriptor

var file_proto_model_attack_scripts_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x5f, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x73, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x22, 0x4b, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x6b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x66, 0x67, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x66, 0x67, 0x49, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x73, 0x22, 0x6d, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x53, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x66, 0x65, 0x74, 0x63, 0x68, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0c, 0x66, 0x65, 0x74, 0x63, 0x68, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73,
	0x22, 0x33, 0x0a, 0x19, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x53,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0xd1, 0x01, 0x0a, 0x0d, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b,
	0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61,
	0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x42, 0x72, 0x0a, 0x1c, 0x63, 0x6f, 0x6d,
	0x2e, 0x67, 0x62, 0x77, 0x33, 0x62, 0x61, 0x6f, 0x2e, 0x73, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x0d, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x6b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x50, 0x01, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0xaa, 0x02, 0x10, 0x53, 0x42, 0x6f, 0x74, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0xca, 0x02, 0x10, 0x53, 0x42, 0x6f,
	0x74, 0x5c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_model_attack_scripts_proto_rawDescOnce sync.Once
	file_proto_model_attack_scripts_proto_rawDescData = file_proto_model_attack_scripts_proto_rawDesc
)

func file_proto_model_attack_scripts_proto_rawDescGZIP() []byte {
	file_proto_model_attack_scripts_proto_rawDescOnce.Do(func() {
		file_proto_model_attack_scripts_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_attack_scripts_proto_rawDescData)
	})
	return file_proto_model_attack_scripts_proto_rawDescData
}

var file_proto_model_attack_scripts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_model_attack_scripts_proto_goTypes = []interface{}{
	(*AddAttackScriptsRequest)(nil),   // 0: sbot.proto.model.AddAttackScriptsRequest
	(*AddAttackScriptsReply)(nil),     // 1: sbot.proto.model.AddAttackScriptsReply
	(*FetchAttackScriptsRequest)(nil), // 2: sbot.proto.model.FetchAttackScriptsRequest
	(*AttackScripts)(nil),             // 3: sbot.proto.model.AttackScripts
}
var file_proto_model_attack_scripts_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_model_attack_scripts_proto_init() }
func file_proto_model_attack_scripts_proto_init() {
	if File_proto_model_attack_scripts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_model_attack_scripts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAttackScriptsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_attack_scripts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAttackScriptsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_attack_scripts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchAttackScriptsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_model_attack_scripts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttackScripts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_attack_scripts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_attack_scripts_proto_goTypes,
		DependencyIndexes: file_proto_model_attack_scripts_proto_depIdxs,
		MessageInfos:      file_proto_model_attack_scripts_proto_msgTypes,
	}.Build()
	File_proto_model_attack_scripts_proto = out.File
	file_proto_model_attack_scripts_proto_rawDesc = nil
	file_proto_model_attack_scripts_proto_goTypes = nil
	file_proto_model_attack_scripts_proto_depIdxs = nil
}
